/**
 ******************************************************************************
  * File Name          : func_timer_list.c
  * Description        : This file is generated by 위대한 송 인재 on Aug 8, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

#define	CONSOLE_SCAN_TIMEOUT	TIMEOUT_10_MSEC
#define	UPTIME_COUNT_TIMEOUT	TIMEOUT_1_SEC

static void console_scan_timeout_cb (void *arg)
{
	osThreadFlagsSet(Thread_CLI_Handler, EF_CONSOLE_SCAN);
}

static void uptime_counter_timeout_cb (void *arg)
{
	uptime_counter++;
}

bool osTimerList_init(osTimerEntry_t osTimerList[])
{
	for (uint32_t i = OS_TIMER_INDEX_BEGIN ; i < OS_TIMER_INDEX_END ; i++) {
		osTimerList[i].osTimerId_t = NULL;
		osTimerList[i].osTimerType = osTimerOnce;
		osTimerList[i].timeout_tick = 0;
		osTimerList[i].timeout_cb = NULL;
		strcpy (osTimerList[i].timer_description, "UNDEFINED TIMER");
	}

	osTimerList[OS_TIMER_INDEX_CLI_CONSOLE_SCAN].osTimerType = osTimerOnce;
	osTimerList[OS_TIMER_INDEX_CLI_CONSOLE_SCAN].timeout_tick = CONSOLE_SCAN_TIMEOUT;
	osTimerList[OS_TIMER_INDEX_CLI_CONSOLE_SCAN].timeout_cb = console_scan_timeout_cb;
	osTimerList[OS_TIMER_INDEX_CLI_CONSOLE_SCAN].osTimerId = osTimerNew(osTimerList[OS_TIMER_INDEX_CLI_CONSOLE_SCAN].timeout_cb, osTimerList[OS_TIMER_INDEX_CLI_CONSOLE_SCAN].timeout_tick, NULL, NULL);
	assert (osTimerList[OS_TIMER_INDEX_CLI_CONSOLE_SCAN].osTimerId != NULL);
	strcpy (osTimerList[OS_TIMER_INDEX_CLI_CONSOLE_SCAN].timer_description, "OS_TIMER_INDEX_CLI_CONSOLE_SCAN");

	osTimerList[OS_TIMER_INDEX_UPTIME_COUNT].osTimerType = osTimerPeriodic;
	osTimerList[OS_TIMER_INDEX_UPTIME_COUNT].timeout_tick = UPTIME_COUNT_TIMEOUT;
	osTimerList[OS_TIMER_INDEX_UPTIME_COUNT].timeout_cb = uptime_counter_timeout_cb;
	osTimerList[OS_TIMER_INDEX_UPTIME_COUNT].osTimerId = osTimerNew(osTimerList[OS_TIMER_INDEX_UPTIME_COUNT].timeout_cb, osTimerList[OS_TIMER_INDEX_UPTIME_COUNT].timeout_tick, NULL, NULL);
	assert (osTimerList[OS_TIMER_INDEX_UPTIME_COUNT].osTimerId != NULL);
	strcpy (osTimerList[OS_TIMER_INDEX_UPTIME_COUNT].timer_description, "OS_TIMER_INDEX_UPTIME_COUNT");


	return true;
}
