/**
 ******************************************************************************
  * File Name          : func_timer_list.c
  * Description        : This file is generated by 위대한 송 인재 on Aug 8, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

#define	CONSOLE_SCAN_TIMEOUT	TIMEOUT_10_MSEC
#define	UPTIME_COUNT_TIMEOUT	TIMEOUT_1_SEC
#define	DOOR_CHECK_TIMEOUT		TIMEOUT_100_MSEC
#define	HT_CHECK_TIMEOUT		TIMEOUT_1_SEC
#define	ADC_CHECK_TIMEOUT		TIMEOUT_1_SEC
#define	INFO_DISPLAY_TIMEOUT	TIMEOUT_1_SEC


static void console_scan_timeout_cb (void *arg)
{
	osThreadFlagsSet(Thread_CLI_Handler, EF_CONSOLE_SCAN);
}

static void uptime_counter_timeout_cb (void *arg)
{
	uptime_counter++;
	assert (HAL_RTC_GetTime(&hrtc, &scw_infoObj.currentTime, RTC_FORMAT_BIN) == HAL_OK);
	assert (HAL_RTC_GetDate(&hrtc, &scw_infoObj.currentDate, RTC_FORMAT_BIN) == HAL_OK);
}

static void door_check_timeout_cb (void *arg)
{
	sensor_msg_t sensor_msg;
	sensor_msg.head.type = SENSOR_MSG_DOOR_CHECK;
	sensor_msg.head.dst = WORKM_SENSOR;
	sensor_msg.head.src = WORKM_TIMER;
	sensor_msg.head.len = 0;
	osMessageQueuePut(sensorThreadQ, &sensor_msg, 0U, 0U);
}

static void ht_check_timeout_cb (void *arg)
{
	sensor_msg_t sensor_msg;
	sensor_msg.head.type = SENSOR_MSG_HM_CHECK;
	sensor_msg.head.dst = WORKM_SENSOR;
	sensor_msg.head.src = WORKM_TIMER;
	sensor_msg.head.len = 0;
	osMessageQueuePut(sensorThreadQ, &sensor_msg, 0U, 0U);
}

static void adc_check_timeout_cb (void *arg)
{
	sensor_msg_t sensor_msg;
	sensor_msg.head.type = SENSOR_MSG_ADC_CHECK;
	sensor_msg.head.dst = WORKM_SENSOR;
	sensor_msg.head.src = WORKM_TIMER;
	sensor_msg.head.len = 0;
	osMessageQueuePut(sensorThreadQ, &sensor_msg, 0U, 0U);
}

static void info_display_timeout_cb (void *arg)
{
	sensor_msg_t sensor_msg;
	sensor_msg.head.type = SENSOR_MSG_INFO_DISPLAY;
	sensor_msg.head.dst = WORKM_SENSOR;
	sensor_msg.head.src = WORKM_TIMER;
	sensor_msg.head.len = 0;
	osMessageQueuePut(sensorThreadQ, &sensor_msg, 0U, 0U);
}

bool osTimerList_init(osTimerEntry_t osTimerList[])
{
	for (uint32_t i = OS_TIMER_INDEX_BEGIN ; i < OS_TIMER_INDEX_END ; i++) {
		osTimerList[i].osTimerId_t = NULL;
		osTimerList[i].osTimerType = osTimerOnce;
		osTimerList[i].timeout_tick = 0;
		osTimerList[i].timeout_cb = NULL;
		strcpy (osTimerList[i].timer_description, "UNDEFINED TIMER");
	}

	osTimerList[OS_TIMER_INDEX_CLI_CONSOLE_SCAN].osTimerType = osTimerOnce;
	osTimerList[OS_TIMER_INDEX_CLI_CONSOLE_SCAN].timeout_tick = CONSOLE_SCAN_TIMEOUT;
	osTimerList[OS_TIMER_INDEX_CLI_CONSOLE_SCAN].timeout_cb = console_scan_timeout_cb;
	osTimerList[OS_TIMER_INDEX_CLI_CONSOLE_SCAN].osTimerId = osTimerNew(osTimerList[OS_TIMER_INDEX_CLI_CONSOLE_SCAN].timeout_cb, osTimerList[OS_TIMER_INDEX_CLI_CONSOLE_SCAN].timeout_tick, NULL, NULL);
	assert (osTimerList[OS_TIMER_INDEX_CLI_CONSOLE_SCAN].osTimerId != NULL);
	strcpy (osTimerList[OS_TIMER_INDEX_CLI_CONSOLE_SCAN].timer_description, "OS_TIMER_INDEX_CLI_CONSOLE_SCAN");

	osTimerList[OS_TIMER_INDEX_UPTIME_COUNT].osTimerType = osTimerPeriodic;
	osTimerList[OS_TIMER_INDEX_UPTIME_COUNT].timeout_tick = UPTIME_COUNT_TIMEOUT;
	osTimerList[OS_TIMER_INDEX_UPTIME_COUNT].timeout_cb = uptime_counter_timeout_cb;
	osTimerList[OS_TIMER_INDEX_UPTIME_COUNT].osTimerId = osTimerNew(osTimerList[OS_TIMER_INDEX_UPTIME_COUNT].timeout_cb, osTimerList[OS_TIMER_INDEX_UPTIME_COUNT].timeout_tick, NULL, NULL);
	assert (osTimerList[OS_TIMER_INDEX_UPTIME_COUNT].osTimerId != NULL);
	strcpy (osTimerList[OS_TIMER_INDEX_UPTIME_COUNT].timer_description, "OS_TIMER_INDEX_UPTIME_COUNT");

	osTimerList[OS_TIMER_INDEX_DOOR_CHECK].osTimerType = osTimerOnce;
	osTimerList[OS_TIMER_INDEX_DOOR_CHECK].timeout_tick = DOOR_CHECK_TIMEOUT;
	osTimerList[OS_TIMER_INDEX_DOOR_CHECK].timeout_cb = door_check_timeout_cb;
	osTimerList[OS_TIMER_INDEX_DOOR_CHECK].osTimerId = osTimerNew(osTimerList[OS_TIMER_INDEX_DOOR_CHECK].timeout_cb, osTimerList[OS_TIMER_INDEX_DOOR_CHECK].timeout_tick, NULL, NULL);
	assert (osTimerList[OS_TIMER_INDEX_DOOR_CHECK].osTimerId != NULL);
	strcpy (osTimerList[OS_TIMER_INDEX_DOOR_CHECK].timer_description, "OS_TIMER_INDEX_DOOR_CHECK");

	osTimerList[OS_TIMER_INDEX_HT_CHECK].osTimerType = osTimerOnce;
	osTimerList[OS_TIMER_INDEX_HT_CHECK].timeout_tick = HT_CHECK_TIMEOUT;
	osTimerList[OS_TIMER_INDEX_HT_CHECK].timeout_cb = ht_check_timeout_cb;
	osTimerList[OS_TIMER_INDEX_HT_CHECK].osTimerId = osTimerNew(osTimerList[OS_TIMER_INDEX_HT_CHECK].timeout_cb, osTimerList[OS_TIMER_INDEX_HT_CHECK].timeout_tick, NULL, NULL);
	assert (osTimerList[OS_TIMER_INDEX_HT_CHECK].osTimerId != NULL);
	strcpy (osTimerList[OS_TIMER_INDEX_HT_CHECK].timer_description, "OS_TIMER_INDEX_HT_CHECK");

	osTimerList[OS_TIMER_INDEX_ADC_CHECK].osTimerType = osTimerOnce;
	osTimerList[OS_TIMER_INDEX_ADC_CHECK].timeout_tick = ADC_CHECK_TIMEOUT;
	osTimerList[OS_TIMER_INDEX_ADC_CHECK].timeout_cb = adc_check_timeout_cb;
	osTimerList[OS_TIMER_INDEX_ADC_CHECK].osTimerId = osTimerNew(osTimerList[OS_TIMER_INDEX_ADC_CHECK].timeout_cb, osTimerList[OS_TIMER_INDEX_ADC_CHECK].timeout_tick, NULL, NULL);
	assert (osTimerList[OS_TIMER_INDEX_ADC_CHECK].osTimerId != NULL);
	strcpy (osTimerList[OS_TIMER_INDEX_ADC_CHECK].timer_description, "OS_TIMER_INDEX_ADC_CHECK");

	osTimerList[OS_TIMER_INDEX_SCW_INFO_DISPLAY].osTimerType = osTimerOnce;
	osTimerList[OS_TIMER_INDEX_SCW_INFO_DISPLAY].timeout_tick = INFO_DISPLAY_TIMEOUT;
	osTimerList[OS_TIMER_INDEX_SCW_INFO_DISPLAY].timeout_cb = info_display_timeout_cb;
	osTimerList[OS_TIMER_INDEX_SCW_INFO_DISPLAY].osTimerId = osTimerNew(osTimerList[OS_TIMER_INDEX_SCW_INFO_DISPLAY].timeout_cb, osTimerList[OS_TIMER_INDEX_SCW_INFO_DISPLAY].timeout_tick, NULL, NULL);
	assert (osTimerList[OS_TIMER_INDEX_SCW_INFO_DISPLAY].osTimerId != NULL);
	strcpy (osTimerList[OS_TIMER_INDEX_SCW_INFO_DISPLAY].timer_description, "OS_TIMER_INDEX_SCW_INFO_DISPLAY");

	return true;
}
