/**
 ******************************************************************************
  * File Name          : func_sensor.c
  * Description        : This file is generated by 위대한 송 인재 on Aug 11, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

extern sensor_msg_func sensor_msg_handler_tbl[SENSOR_MSG_END];

static bool sensor_msg_handler_default(sensor_msg_t *pq_msg)
{
	char sensor_msg[100];

	switch (pq_msg->head.type) {
	case SENSOR_MSG_BASE : strcpy (sensor_msg, "SENSOR_MSG_BASE"); break;
	case SENSOR_MSG_DOOR_CHECK : strcpy (sensor_msg, "SENSOR_MSG_DOOR_CHECK"); break;
	case SENSOR_MSG_END : strcpy (sensor_msg, "SENSOR_MSG_END"); break;
	default : strcpy (sensor_msg, "UNKNOWN type"); break;
	}

	printf("%s() : sensor_msg_type = %s"LINE_TERM, __FUNCTION__, sensor_msg);

	return true;
}

scw_door_status_t get_door_1_status()
{
	scw_door_status_t Door1_state;
	Door1_state = (HAL_GPIO_ReadPin(DOOR_1_GPIO_Port, DOOR_1_Pin) == GPIO_PIN_SET)?SCW_DOOR_CLOSED:SCW_DOOR_OPEN;
	return Door1_state;
}

scw_door_status_t get_door_2_status()
{
	scw_door_status_t Door2_state;
	Door2_state = (HAL_GPIO_ReadPin(DOOR_2_GPIO_Port, DOOR_2_Pin) == GPIO_PIN_SET)?SCW_DOOR_CLOSED:SCW_DOOR_OPEN;
	return Door2_state;
}

static bool sensor_msg_handler_door_check(sensor_msg_t *pq_msg)
{
	UNUSED(pq_msg);
//
//	if (scw_infoObj.scw_door.door_1_status != get_door_1_status()) {
//		printf(" Door1_state -> %s"LINE_TERM, (get_door_1_status() == SCW_DOOR_OPEN)?"OPEN":"CLOSED");
//	}
//
//	if (scw_infoObj.scw_door.door_2_status != get_door_2_status()) {
//		printf(" Door2_state -> %s"LINE_TERM, (get_door_2_status() == SCW_DOOR_OPEN)?"OPEN":"CLOSED");
//	}

	scw_infoObj.scw_door.door_1_status = get_door_1_status();
	scw_infoObj.scw_door.door_2_status = get_door_2_status();

	assert (osTimerStart(osTimerList[OS_TIMER_INDEX_DOOR_CHECK].osTimerId, osTimerList[OS_TIMER_INDEX_DOOR_CHECK].timeout_tick) == osOK);

	return true;
}

static bool sensor_msg_handler_ht_check(sensor_msg_t *pq_msg)
{
	UNUSED(pq_msg);

	scw_infoObj.SHT20_INFO.m_tempreture = SHT2x_GetTemperature(1);
	scw_infoObj.SHT20_INFO.m_humidity = SHT2x_GetRelativeHumidity(1);

#if 0
	// 아래 루틴은 annex 로 ...
	/* Gets current temperature & relative humidity. */
	float cel = SHT2x_GetTemperature(1);
	/* Converts temperature to degrees Fahrenheit and Kelvin */
	float fah = SHT2x_CelsiusToFahrenheit(cel);
	float kel = SHT2x_CelsiusToKelvin(cel);
	float rh = SHT2x_GetRelativeHumidity(1);
	/* May show warning below. Ignore and proceed. */
	printf(	"%ld.%ldºC, %ld.%ldºF, %ld.%ld K, %ld.%ld%% RH"LINE_TERM,
			SHT2x_GetInteger(cel), SHT2x_GetDecimal(cel, 1),
			SHT2x_GetInteger(fah), SHT2x_GetDecimal(fah, 1),
			SHT2x_GetInteger(kel), SHT2x_GetDecimal(kel, 1),
			SHT2x_GetInteger(rh), SHT2x_GetDecimal(rh, 1));
#endif
	assert (osTimerStart(osTimerList[OS_TIMER_INDEX_HT_CHECK].osTimerId, osTimerList[OS_TIMER_INDEX_HT_CHECK].timeout_tick) == osOK);

	return true;
}

static bool sensor_msg_handler_adc_check(sensor_msg_t *pq_msg)
{
	UNUSED(pq_msg);
	assert (HAL_ADC_Start_DMA(&hadc1, (uint32_t *)aADCxConvertedData, ADC_CONVERTED_DATA_BUFFER_SIZE) == HAL_OK);
	assert (osTimerStart(osTimerList[OS_TIMER_INDEX_ADC_CHECK].osTimerId, osTimerList[OS_TIMER_INDEX_ADC_CHECK].timeout_tick) == osOK);

	return true;
}

static bool sensor_msg_handler_info_display(sensor_msg_t *pq_msg)
{
	UNUSED(pq_msg);
	if (do_scw_info_display == true) {
		printf (RTT_COLOR_CODE_CYAN);
		printf (CUI_ESC_CUR_HOME); osDelay(1);
		printf ("***************************************************"LINE_TERM);
		printf ("*                                                 *"LINE_TERM);
		printf ("*             Smart Crosswalk Status              *"LINE_TERM);
		printf ("*                                                 *"LINE_TERM);
		printf ("***************************************************"LINE_TERM);
		printf (RTT_COLOR_CODE_DEFAULT);

		printf("fw_version \t= %s"LINE_TERM, scw_infoObj.fw_version);

		if (scw_infoObj.implementer == 0x41) printf("implementer \t= Arm"LINE_TERM);
		if (scw_infoObj.partno == 0xC24) printf("partno \t\t= Cortex-M4"LINE_TERM);

		printf ("uid0 \t\t= %#010"PRIx32 LINE_TERM, scw_infoObj.uid0);
		printf ("uid1 \t\t= %#010"PRIx32 LINE_TERM, scw_infoObj.uid1);
		printf ("uid2 \t\t= %#010"PRIx32 LINE_TERM, scw_infoObj.uid2);
		printf(LINE_TERM);

		printf("Time \t\t= %2d:%2d:%2d %s"LINE_TERM, \
				scw_infoObj.currentTime.Hours, scw_infoObj.currentTime.Minutes, scw_infoObj.currentTime.Seconds, (scw_infoObj.currentTime.Hours < 12)?"am":"pm");

		printf(LINE_TERM);
		printf("door_1 = %s"LINE_TERM, (scw_infoObj.scw_door.door_1_status == SCW_DOOR_OPEN)?"SCW_DOOR_OPEN  ":"SCW_DOOR_CLOSED");
		printf("door_2 = %s"LINE_TERM, (scw_infoObj.scw_door.door_2_status == SCW_DOOR_OPEN)?"SCW_DOOR_OPEN  ":"SCW_DOOR_CLOSED");

		printf(LINE_TERM"Ondo/Humidity"LINE_TERM);
		/* Gets current temperature & relative humidity. */
		float cel = SHT2x_GetTemperature(1);
		/* Converts temperature to degrees Fahrenheit and Kelvin */
		float fah = SHT2x_CelsiusToFahrenheit(cel);
		float kel = SHT2x_CelsiusToKelvin(cel);
		float rh = SHT2x_GetRelativeHumidity(1);
		/* May show warning below. Ignore and proceed. */
		printf(	" Ondo = %ld.%ldºC, %ld.%ldºF, %ld.%ld K, Humidity = %ld.%ld%% RH"LINE_TERM,
				SHT2x_GetInteger(cel), SHT2x_GetDecimal(cel, 1),
				SHT2x_GetInteger(fah), SHT2x_GetDecimal(fah, 1),
				SHT2x_GetInteger(kel), SHT2x_GetDecimal(kel, 1),
				SHT2x_GetInteger(rh), SHT2x_GetDecimal(rh, 1));

		printf(LINE_TERM"ADC"LINE_TERM);
		printf(" AD1 = %d"LINE_TERM, scw_infoObj.scw_adc_value.AD1);
		printf(" AD2 = %d"LINE_TERM, scw_infoObj.scw_adc_value.AD2);
		printf(" AD3 = %d"LINE_TERM, scw_infoObj.scw_adc_value.AD3);
		printf(" AD4 = %d"LINE_TERM, scw_infoObj.scw_adc_value.AD4);

		{
			uint8_t day, hour, min, sec;
			uint64_t tmp;
			tmp = uptime_counter;

			day = tmp /DAY_TO_SEC;
			tmp = tmp - (day*DAY_TO_SEC);

			hour = tmp/HOUR_TO_SEC;
			tmp = tmp - (hour*HOUR_TO_SEC);

			min = tmp/MIN_TO_SEC;
			tmp = tmp - (min*MIN_TO_SEC);

			sec = tmp;
			printf(LINE_TERM"Uptime : %d days, %d hours, %d mins, %d sec"LINE_TERM, day, hour, min, sec);
		}

	}

	return true;
}

bool sensor_msg_handler_tbl_init()
{
	for (uint32_t i = 0 ; i < SENSOR_MSG_END ; i++) {
		sensor_msg_handler_tbl[i] = sensor_msg_handler_default;
	}

	sensor_msg_handler_tbl[SENSOR_MSG_DOOR_CHECK] = sensor_msg_handler_door_check;
	sensor_msg_handler_tbl[SENSOR_MSG_HM_CHECK] = sensor_msg_handler_ht_check;
	sensor_msg_handler_tbl[SENSOR_MSG_ADC_CHECK] = sensor_msg_handler_adc_check;
	sensor_msg_handler_tbl[SENSOR_MSG_INFO_DISPLAY] = sensor_msg_handler_info_display;

	return true;
}
