/**
 ******************************************************************************
  * File Name          : func_intr_list.c
  * Description        : This file is generated by 위대한 송 인재 on Aug 11, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

bool IntrList_init(IntrObjEntry_t IntrObjEntryList[])
{
	for (uint32_t i = SCW_RTU_INTR_INDEX_BEGIN ; i < SCW_RTU_INTR_INDEX_END ; i++) {
		IntrObjEntryList[i].IntrNo = i;
		IntrObjEntryList[i].IntrCount = 0;
		strcpy (IntrObjEntryList[i].IntrName, "UNUSED INTERRUPT");
		strcpy (IntrObjEntryList[i].IntrDesc, "UNUSED INTERRUPT");
	}

	strcpy (IntrObjEntryList[WWDG_IRQn].IntrName, "WWDG_IRQn");
	strcpy (IntrObjEntryList[PVD_IRQn].IntrName, "PVD_IRQn");
	strcpy (IntrObjEntryList[TAMPER_IRQn].IntrName, "TAMPER_IRQn");
	strcpy (IntrObjEntryList[RTC_IRQn].IntrName, "RTC_IRQn");
	strcpy (IntrObjEntryList[FLASH_IRQn].IntrName, "FLASH_IRQn");
	strcpy (IntrObjEntryList[RCC_IRQn].IntrName, "RCC_IRQn");
	strcpy (IntrObjEntryList[EXTI0_IRQn].IntrName, "EXTI0_IRQn");
	strcpy (IntrObjEntryList[EXTI1_IRQn].IntrName, "EXTI1_IRQn");
	strcpy (IntrObjEntryList[EXTI2_IRQn].IntrName, "EXTI2_IRQn");
	strcpy (IntrObjEntryList[EXTI3_IRQn].IntrName, "EXTI3_IRQn");
	strcpy (IntrObjEntryList[EXTI4_IRQn].IntrName, "EXTI4_IRQn");
	strcpy (IntrObjEntryList[DMA1_Channel1_IRQn].IntrName, "DMA1_Channel1_IRQn");
	strcpy (IntrObjEntryList[DMA1_Channel2_IRQn].IntrName, "DMA1_Channel2_IRQn");
	strcpy (IntrObjEntryList[DMA1_Channel3_IRQn].IntrName, "DMA1_Channel3_IRQn");
	strcpy (IntrObjEntryList[DMA1_Channel4_IRQn].IntrName, "DMA1_Channel4_IRQn");
	strcpy (IntrObjEntryList[DMA1_Channel5_IRQn].IntrName, "DMA1_Channel5_IRQn");
	strcpy (IntrObjEntryList[DMA1_Channel6_IRQn].IntrName, "DMA1_Channel6_IRQn");
	strcpy (IntrObjEntryList[DMA1_Channel7_IRQn].IntrName, "DMA1_Channel7_IRQn");
	strcpy (IntrObjEntryList[ADC1_2_IRQn].IntrName, "ADC1_2_IRQn");
	strcpy (IntrObjEntryList[USB_HP_CAN1_TX_IRQn].IntrName, "USB_HP_CAN1_TX_IRQn");
	strcpy (IntrObjEntryList[USB_LP_CAN1_RX0_IRQn].IntrName, "USB_LP_CAN1_RX0_IRQn");
	strcpy (IntrObjEntryList[CAN1_RX1_IRQn].IntrName, "CAN1_RX1_IRQn");
	strcpy (IntrObjEntryList[CAN1_SCE_IRQn].IntrName, "CAN1_SCE_IRQn");
	strcpy (IntrObjEntryList[EXTI9_5_IRQn].IntrName, "EXTI9_5_IRQn");
	strcpy (IntrObjEntryList[TIM1_BRK_IRQn].IntrName, "TIM1_BRK_IRQn");
	strcpy (IntrObjEntryList[TIM1_UP_IRQn].IntrName, "TIM1_UP_IRQn");
	strcpy (IntrObjEntryList[TIM1_TRG_COM_IRQn].IntrName, "TIM1_TRG_COM_IRQn");
	strcpy (IntrObjEntryList[TIM1_CC_IRQn].IntrName, "TIM1_CC_IRQn");
	strcpy (IntrObjEntryList[TIM2_IRQn].IntrName, "TIM2_IRQn");
	strcpy (IntrObjEntryList[TIM3_IRQn].IntrName, "TIM3_IRQn");
	strcpy (IntrObjEntryList[TIM4_IRQn].IntrName, "TIM4_IRQn");
	strcpy (IntrObjEntryList[I2C1_EV_IRQn].IntrName, "I2C1_EV_IRQn");
	strcpy (IntrObjEntryList[I2C1_ER_IRQn].IntrName, "I2C1_ER_IRQn");
	strcpy (IntrObjEntryList[I2C2_EV_IRQn].IntrName, "I2C2_EV_IRQn");
	strcpy (IntrObjEntryList[I2C2_ER_IRQn].IntrName, "I2C2_ER_IRQn");
	strcpy (IntrObjEntryList[SPI1_IRQn].IntrName, "SPI1_IRQn");
	strcpy (IntrObjEntryList[SPI2_IRQn].IntrName, "SPI2_IRQn");
	strcpy (IntrObjEntryList[USART1_IRQn].IntrName, "USART1_IRQn");
	strcpy (IntrObjEntryList[USART2_IRQn].IntrName, "USART2_IRQn");
	strcpy (IntrObjEntryList[USART3_IRQn].IntrName, "USART3_IRQn");
	strcpy (IntrObjEntryList[EXTI15_10_IRQn].IntrName, "EXTI15_10_IRQn");
	strcpy (IntrObjEntryList[RTC_Alarm_IRQn].IntrName, "RTC_Alarm_IRQn");
	strcpy (IntrObjEntryList[USBWakeUp_IRQn].IntrName, "USBWakeUp_IRQn");
	strcpy (IntrObjEntryList[TIM8_BRK_IRQn].IntrName, "TIM8_BRK_IRQn");
	strcpy (IntrObjEntryList[TIM8_UP_IRQn].IntrName, "TIM8_UP_IRQn");
	strcpy (IntrObjEntryList[TIM8_TRG_COM_IRQn].IntrName, "TIM8_TRG_COM_IRQn");
	strcpy (IntrObjEntryList[TIM8_CC_IRQn].IntrName, "TIM8_CC_IRQn");
	strcpy (IntrObjEntryList[ADC3_IRQn].IntrName, "ADC3_IRQn");
	strcpy (IntrObjEntryList[FSMC_IRQn].IntrName, "FSMC_IRQn");
	strcpy (IntrObjEntryList[SDIO_IRQn].IntrName, "SDIO_IRQn");
	strcpy (IntrObjEntryList[TIM5_IRQn].IntrName, "TIM5_IRQn");
	strcpy (IntrObjEntryList[SPI3_IRQn].IntrName, "SPI3_IRQn");
	strcpy (IntrObjEntryList[UART4_IRQn].IntrName, "UART4_IRQn");
	strcpy (IntrObjEntryList[UART5_IRQn].IntrName, "UART5_IRQn");
	strcpy (IntrObjEntryList[TIM6_IRQn].IntrName, "TIM6_IRQn");
	strcpy (IntrObjEntryList[TIM7_IRQn].IntrName, "TIM7_IRQn");
	strcpy (IntrObjEntryList[DMA2_Channel1_IRQn].IntrName, "DMA2_Channel1_IRQn");
	strcpy (IntrObjEntryList[DMA2_Channel2_IRQn].IntrName, "DMA2_Channel2_IRQn");
	strcpy (IntrObjEntryList[DMA2_Channel3_IRQn].IntrName, "DMA2_Channel3_IRQn");
	strcpy (IntrObjEntryList[DMA2_Channel4_5_IRQn].IntrName, "DMA2_Channel4_5_IRQn");

	strcpy (IntrObjEntryList[WWDG_IRQn].IntrDesc, "WWDG_IRQn");
	strcpy (IntrObjEntryList[PVD_IRQn].IntrDesc, "PVD_IRQn");
	strcpy (IntrObjEntryList[TAMPER_IRQn].IntrDesc, "TAMPER_IRQn");
	strcpy (IntrObjEntryList[RTC_IRQn].IntrDesc, "RTC_IRQn");
	strcpy (IntrObjEntryList[FLASH_IRQn].IntrDesc, "FLASH_IRQn");
	strcpy (IntrObjEntryList[RCC_IRQn].IntrDesc, "RCC_IRQn");
	strcpy (IntrObjEntryList[EXTI0_IRQn].IntrDesc, "EXTI0_IRQn");
	strcpy (IntrObjEntryList[EXTI1_IRQn].IntrDesc, "EXTI1_IRQn");
	strcpy (IntrObjEntryList[EXTI2_IRQn].IntrDesc, "EXTI2_IRQn");
	strcpy (IntrObjEntryList[EXTI3_IRQn].IntrDesc, "EXTI3_IRQn");
	strcpy (IntrObjEntryList[EXTI4_IRQn].IntrDesc, "EXTI4_IRQn");
	strcpy (IntrObjEntryList[DMA1_Channel1_IRQn].IntrDesc, "DMA1_Channel1_IRQn");
	strcpy (IntrObjEntryList[DMA1_Channel2_IRQn].IntrDesc, "DMA1_Channel2_IRQn");
	strcpy (IntrObjEntryList[DMA1_Channel3_IRQn].IntrDesc, "DMA1_Channel3_IRQn");
	strcpy (IntrObjEntryList[DMA1_Channel4_IRQn].IntrDesc, "DMA1_Channel4_IRQn");
	strcpy (IntrObjEntryList[DMA1_Channel5_IRQn].IntrDesc, "DMA1_Channel5_IRQn");
	strcpy (IntrObjEntryList[DMA1_Channel6_IRQn].IntrDesc, "DMA1_Channel6_IRQn");
	strcpy (IntrObjEntryList[DMA1_Channel7_IRQn].IntrDesc, "DMA1_Channel7_IRQn");
	strcpy (IntrObjEntryList[ADC1_2_IRQn].IntrDesc, "ADC1_2_IRQn");
	strcpy (IntrObjEntryList[USB_HP_CAN1_TX_IRQn].IntrDesc, "USB_HP_CAN1_TX_IRQn");
	strcpy (IntrObjEntryList[USB_LP_CAN1_RX0_IRQn].IntrDesc, "USB_LP_CAN1_RX0_IRQn");
	strcpy (IntrObjEntryList[CAN1_RX1_IRQn].IntrDesc, "CAN1_RX1_IRQn");
	strcpy (IntrObjEntryList[CAN1_SCE_IRQn].IntrDesc, "CAN1_SCE_IRQn");
	strcpy (IntrObjEntryList[EXTI9_5_IRQn].IntrDesc, "EXTI9_5_IRQn");
	strcpy (IntrObjEntryList[TIM1_BRK_IRQn].IntrDesc, "TIM1_BRK_IRQn");
	strcpy (IntrObjEntryList[TIM1_UP_IRQn].IntrDesc, "TIM1_UP_IRQn");
	strcpy (IntrObjEntryList[TIM1_TRG_COM_IRQn].IntrDesc, "TIM1_TRG_COM_IRQn");
	strcpy (IntrObjEntryList[TIM1_CC_IRQn].IntrDesc, "TIM1_CC_IRQn");
	strcpy (IntrObjEntryList[TIM2_IRQn].IntrDesc, "TIM2_IRQn");
	strcpy (IntrObjEntryList[TIM3_IRQn].IntrDesc, "TIM3_IRQn");
	strcpy (IntrObjEntryList[TIM4_IRQn].IntrDesc, "TIM4_IRQn");
	strcpy (IntrObjEntryList[I2C1_EV_IRQn].IntrDesc, "I2C1_EV_IRQn");
	strcpy (IntrObjEntryList[I2C1_ER_IRQn].IntrDesc, "I2C1_ER_IRQn");
	strcpy (IntrObjEntryList[I2C2_EV_IRQn].IntrDesc, "I2C2_EV_IRQn");
	strcpy (IntrObjEntryList[I2C2_ER_IRQn].IntrDesc, "I2C2_ER_IRQn");
	strcpy (IntrObjEntryList[SPI1_IRQn].IntrDesc, "SPI1_IRQn");
	strcpy (IntrObjEntryList[SPI2_IRQn].IntrDesc, "SPI2_IRQn");
	strcpy (IntrObjEntryList[USART1_IRQn].IntrDesc, "USART1_IRQn");
	strcpy (IntrObjEntryList[USART2_IRQn].IntrDesc, "USART2_IRQn");
	strcpy (IntrObjEntryList[USART3_IRQn].IntrDesc, "USART3_IRQn");
	strcpy (IntrObjEntryList[EXTI15_10_IRQn].IntrDesc, "EXTI15_10_IRQn");
	strcpy (IntrObjEntryList[RTC_Alarm_IRQn].IntrDesc, "RTC_Alarm_IRQn");
	strcpy (IntrObjEntryList[USBWakeUp_IRQn].IntrDesc, "USBWakeUp_IRQn");
	strcpy (IntrObjEntryList[TIM8_BRK_IRQn].IntrDesc, "TIM8_BRK_IRQn");
	strcpy (IntrObjEntryList[TIM8_UP_IRQn].IntrDesc, "TIM8_UP_IRQn");
	strcpy (IntrObjEntryList[TIM8_TRG_COM_IRQn].IntrDesc, "TIM8_TRG_COM_IRQn");
	strcpy (IntrObjEntryList[TIM8_CC_IRQn].IntrDesc, "TIM8_CC_IRQn");
	strcpy (IntrObjEntryList[ADC3_IRQn].IntrDesc, "ADC3_IRQn");
	strcpy (IntrObjEntryList[FSMC_IRQn].IntrDesc, "FSMC_IRQn");
	strcpy (IntrObjEntryList[SDIO_IRQn].IntrDesc, "SDIO_IRQn");
	strcpy (IntrObjEntryList[TIM5_IRQn].IntrDesc, "TIM5_IRQn");
	strcpy (IntrObjEntryList[SPI3_IRQn].IntrDesc, "SPI3_IRQn");
	strcpy (IntrObjEntryList[UART4_IRQn].IntrDesc, "UART4_IRQn");
	strcpy (IntrObjEntryList[UART5_IRQn].IntrDesc, "UART5_IRQn");
	strcpy (IntrObjEntryList[TIM6_IRQn].IntrDesc, "TIM6_IRQn");
	strcpy (IntrObjEntryList[TIM7_IRQn].IntrDesc, "TIM7_IRQn");
	strcpy (IntrObjEntryList[DMA2_Channel1_IRQn].IntrDesc, "DMA2_Channel1_IRQn");
	strcpy (IntrObjEntryList[DMA2_Channel2_IRQn].IntrDesc, "DMA2_Channel2_IRQn");
	strcpy (IntrObjEntryList[DMA2_Channel3_IRQn].IntrDesc, "DMA2_Channel3_IRQn");
	strcpy (IntrObjEntryList[DMA2_Channel4_5_IRQn].IntrDesc, "DMA2_Channel4_5_IRQn");



	return true;
}
