/**
 ******************************************************************************
  * File Name          : func_intr_list.c
  * Description        : This file is generated by 위대한 송 인재 on Aug 11, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"


#if 0
typedef struct {
	uint32_t			IntrNo;
	uint32_t			IntrCount;
	char				IntrName[50];
	char				IntrDesc[50];
} IntrObjEntry_t;


#endif
IntrObjEntry_t	IntrObjEntryList[SCW_RTU_INTR_INDEX_END] = {
		{true,		0,			"WWDG_IRQn",				"WWDG_IRQn"},
//		{false,		0,			"PVD_IRQn",					"PVD_IRQn"},
//		{false,		0,			"TAMPER_IRQn",				"TAMPER_IRQn"},
		{true,		0,			"RTC_IRQn",					"RTC_IRQn"},
//		{false,		0,			"FLASH_IRQn",				"FLASH_IRQn"},
//		{false,		0,			"RCC_IRQn",					"RCC_IRQn"},
//		{false,		0,			"EXTI0_IRQn",				"EXTI0_IRQn"},
//		{false,		0,			"EXTI1_IRQn",				"EXTI1_IRQn"},
//		{false,		0,			"EXTI2_IRQn",				"EXTI2_IRQn"},
//		{false,		0,			"EXTI3_IRQn",				"EXTI3_IRQn"},
//
//		{false,		0,			"EXTI4_IRQn",				"EXTI4_IRQn"},
		{true,		0,			"DMA1_Channel1_IRQn",		"ADC1 Intr"},
//		{false,		0,			"DMA1_Channel2_IRQn",		"DMA1_Channel2_IRQn"},
//		{false,		0,			"DMA1_Channel3_IRQn",		"DMA1_Channel3_IRQn"},
		{true,		0,			"DMA1_Channel4_IRQn",		"Console Rx DMA"},
//		{false,		0,			"DMA1_Channel5_IRQn",		"DMA1_Channel5_IRQn"},
//		{false,		0,			"DMA1_Channel6_IRQn",		"DMA1_Channel6_IRQn"},
//		{false,		0,			"DMA1_Channel7_IRQn",		"DMA1_Channel7_IRQn"},
		{true,		0,			"ADC1_2_IRQn",				"ADC1_2_IRQn"},
//		{false,		0,			"USB_HP_CAN1_TX_IRQn",		"USB_HP_CAN1_TX_IRQn"},
//		{false,		0,			"USB_LP_CAN1_RX0_IRQn",		"USB_LP_CAN1_RX0_IRQn"},
//
//		{false,		0,			"CAN1_RX1_IRQn",			"CAN1_RX1_IRQn"},
//		{false,		0,			"CAN1_SCE_IRQn",			"CAN1_SCE_IRQn"},
//		{false,		0,			"EXTI9_5_IRQn",				"EXTI9_5_IRQn"},
//		{false,		0,			"TIM1_BRK_IRQn",			"TIM1_BRK_IRQn"},
//		{false,		0,			"TIM1_UP_IRQn",				"TIM1_UP_IRQn"},
//		{false,		0,			"TIM1_TRG_COM_IRQn",		"TIM1_TRG_COM_IRQn"},
//		{false,		0,			"TIM1_CC_IRQn",				"TIM1_CC_IRQn"},
//		{false,		0,			"TIM2_IRQn",				"TIM2_IRQn"},
//		{false,		0,			"TIM3_IRQn",				"TIM3_IRQn"},
//
//		{false,		0,			"TIM4_IRQn",				"TIM4_IRQn"},
		{true,		0,			"I2C1_EV_IRQn",				"I2C1_EV_IRQn"},
		{true,		0,			"I2C1_ER_IRQn",				"I2C1_ER_IRQn"},
//		{false,		0,			"I2C2_EV_IRQn",				"I2C2_EV_IRQn"},
//		{false,		0,			"I2C2_ER_IRQn",				"I2C2_ER_IRQn"},
//		{false,		0,			"SPI1_IRQn",				"SPI1_IRQn"},
//		{false,		0,			"SPI2_IRQn",				"SPI2_IRQn"},
		{true,		0,			"USART1_IRQn",				"Console Intr"},
//		{false,		0,			"USART2_IRQn",				"USART2_IRQn"},
//		{false,		0,			"USART3_IRQn",				"USART3_IRQn"},
//
//		{false,		0,			"EXTI15_10_IRQn",			"EXTI15_10_IRQn"},
		{true,		0,			"RTC_Alarm_IRQn",			"RTC_Alarm_IRQn"},
//		{false,		0,			"USBWakeUp_IRQn",			"USBWakeUp_IRQn"},
//		{false,		0,			"TIM8_BRK_IRQn",			"TIM8_BRK_IRQn"},
		{true,		0,			"TIM8_UP_IRQn",				"Timebase"},
//		{false,		0,			"TIM8_TRG_COM_IRQn",		"TIM8_TRG_COM_IRQn"},
//		{false,		0,			"TIM8_CC_IRQn",				"TIM8_CC_IRQn"},
//		{false,		0,			"ADC3_IRQn",				"ADC3_IRQn"},
//		{false,		0,			"FSMC_IRQn",				"FSMC_IRQn"},
//		{false,		0,			"SDIO_IRQn",				"SDIO_IRQn"},
//
//		{false,		0,			"TIM5_IRQn",				"TIM5_IRQn"},
//		{false,		0,			"SPI3_IRQn",				"SPI3_IRQn"},
		{true,		0,			"UART4_IRQn",				"Suji Intr"},
		{true,		0,			"UART5_IRQn",				"UART5_IRQn"},
//		{false,		0,			"TIM6_IRQn",				"TIM6_IRQn"},
//		{false,		0,			"TIM7_IRQn",				"TIM7_IRQn"},
//		{false,		0,			"DMA2_Channel1_IRQn",		"DMA2_Channel1_IRQn"},
//		{false,		0,			"DMA2_Channel2_IRQn",		"DMA2_Channel2_IRQn"},
		{true,		0,			"DMA2_Channel3_IRQn",		"Suji -> RTU"},
		{true,		0,			"DMA2_Channel4_5_IRQn",		"RTU -> Suji"},
};
