/**
 ******************************************************************************
 * File Name          : scw_thread_sensor.c
 * Description        : This file is generated by 위대한 송 인재 on Aug 11, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

#define SENSOR_MSG_Q_DEPTH	8

sensor_msg_func			sensor_msg_handler_tbl[SENSOR_MSG_END];
osMessageQueueId_t		sensorThreadQ;

bool sensor_msg_handler_tbl_init();

static bool door_check_timer_begin ()
{
	assert (osTimerList[OS_TIMER_INDEX_DOOR_CHECK].osTimerId != NULL);
	assert (osTimerStart(osTimerList[OS_TIMER_INDEX_DOOR_CHECK].osTimerId, osTimerList[OS_TIMER_INDEX_DOOR_CHECK].timeout_tick) == osOK);
	return true;
}

static bool ht_check_timer_begin ()
{
	assert (osTimerList[OS_TIMER_INDEX_HT_CHECK].osTimerId != NULL);
	assert (osTimerStart(osTimerList[OS_TIMER_INDEX_HT_CHECK].osTimerId, osTimerList[OS_TIMER_INDEX_HT_CHECK].timeout_tick) == osOK);
	return true;
}

static bool adc_check_timer_begin ()
{
	assert (osTimerList[OS_TIMER_INDEX_ADC_CHECK].osTimerId != NULL);
	assert (osTimerStart(osTimerList[OS_TIMER_INDEX_ADC_CHECK].osTimerId, osTimerList[OS_TIMER_INDEX_ADC_CHECK].timeout_tick) == osOK);
	return true;
}

static bool do_scw_info_display_timer_begin ()
{
	assert (osTimerList[OS_TIMER_INDEX_SCW_INFO_DISPLAY].osTimerId != NULL);
	assert (osTimerStart(osTimerList[OS_TIMER_INDEX_SCW_INFO_DISPLAY].osTimerId, osTimerList[OS_TIMER_INDEX_SCW_INFO_DISPLAY].timeout_tick) == osOK);
	return true;
}

void scw_thread_sensor (void *arg)
{
	sensor_msg_t sensor_msg;

	assert (sensor_msg_handler_tbl_init() == true);
	assert (door_check_timer_begin() == true);
	assert (ht_check_timer_begin() == true);
	assert (adc_check_timer_begin() == true);
	assert (do_scw_info_display_timer_begin() == true);

	sensorThreadQ = osMessageQueueNew(SENSOR_MSG_Q_DEPTH, sizeof(sensor_msg_t), NULL);
	while (1) {
		memset (&sensor_msg, 0, sizeof(sensor_msg));
		assert (osMessageQueueGet(sensorThreadQ, &sensor_msg, NULL, osWaitForever) == osOK);
		assert (sensor_msg.head.type < SENSOR_MSG_END);
		assert (sensor_msg.head.dst == WORKM_SENSOR);
		assert (sensor_msg_handler_tbl[sensor_msg.head.type](&sensor_msg) == true);
	}
}
