/**
 ******************************************************************************
  * File Name          : scw_thread_sj.c
  * Description        : This file is generated by 위대한 송 인재 on Aug 12, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

osMessageQueueId_t		sujiThreadQ;
uint8_t 				SujiRxBuff[SUJI_RX_BUFF_SIZE];
uint8_t 				SujiTxBuff[SUJI_TX_BUFF_SIZE];
suji_msg_func			suji_msg_handler_tbl[SUJI_MSG_END];

extern DMA_HandleTypeDef hdma_uart4_rx;
extern DMA_HandleTypeDef hdma_uart4_tx;
bool suji_msg_handler_tbl_init(void);

bool suji_channel_open (UART_HandleTypeDef *huart)
{
	// Smart Crosswalk 는 UART4 (COM1) 가 Suji (PC board) 와 연결된다.
	assert (huart->Instance == UART4);

	/* Clean the input path */
	assert (HAL_UART_AbortReceive_IT(huart) == HAL_OK);
	__HAL_UART_FLUSH_DRREGISTER(huart);
	assert (HAL_UARTEx_ReceiveToIdle_DMA(huart, SujiRxBuff, SUJI_RX_BUFF_SIZE) == HAL_OK);
	__HAL_DMA_DISABLE_IT(&hdma_uart4_rx, DMA_IT_HT);
	HAL_NVIC_EnableIRQ(UART4_IRQn);

	return true;
}

void scw_thread_suji (void *arg)
{
	suji_msg_t suji_msg;

	assert (suji_msg_handler_tbl_init() == true);
	assert (suji_channel_open(&huart4) == true);

	sujiThreadQ = osMessageQueueNew(SUJI_MSG_Q_DEPTH, sizeof(sensor_msg_t), NULL);
	while (1) {
		memset (&suji_msg, 0, sizeof(suji_msg));
		assert (osMessageQueueGet(sujiThreadQ, &suji_msg, NULL, osWaitForever) == osOK);
		assert (suji_msg.head.type < SUJI_MSG_END);
		assert (suji_msg.head.dst == WORKM_SUJI);
		assert (suji_msg_handler_tbl[suji_msg.head.type](&suji_msg) == true);
	}
}
