/**
 ******************************************************************************
  * File Name          : app_entry.c
  * Description        : This file is generated by 위대한 송 인재 on Aug 8, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

osThreadId_t Thread_INIT_Handler;
osThreadId_t Thread_CLI_Handler;
osThreadId_t Thread_SENSOR_Handler;
osThreadId_t Thread_ANNEX_Handler;

void scw_thread_cli (void *arg);
void scw_thread_annex (void *arg);
void scw_thread_init (void *arg);
void scw_thread_sensor (void *arg);


/******************************************************************************
 * Thread Initial attributes
 ******************************************************************************/
#define CFG_INIT_THREAD_NAME        "THREAD_INIT"
#define CFG_INIT_THREAD_ATTR_BITS   (0)
#define CFG_INIT_THREAD_CB_MEM      (0)
#define CFG_INIT_THREAD_CB_SIZE     (0)
#define CFG_INIT_THREAD_STACK_MEM   (0)
#define CFG_INIT_THREAD_PRIORITY    osPriorityHigh
#define CFG_INIT_THREAD_STACK_SIZE  (configMINIMAL_STACK_SIZE * 32)

const osThreadAttr_t SCW_INIT_Thread_attr = {
		.name = 		CFG_INIT_THREAD_NAME,
		.attr_bits = 	CFG_INIT_THREAD_ATTR_BITS,
		.cb_mem = 		CFG_INIT_THREAD_CB_MEM,
		.cb_size = 		CFG_INIT_THREAD_CB_SIZE,
		.stack_mem = 	CFG_INIT_THREAD_STACK_MEM,
		.priority = 	CFG_INIT_THREAD_PRIORITY,
		.stack_size = 	CFG_INIT_THREAD_STACK_SIZE
};

/******************************************************************************
 * Thread CLI attributes
 ******************************************************************************/
#define CFG_CLI_THREAD_NAME        "THREAD_CLI"
#define CFG_CLI_THREAD_ATTR_BITS   (0)
#define CFG_CLI_THREAD_CB_MEM      (0)
#define CFG_CLI_THREAD_CB_SIZE     (0)
#define CFG_CLI_THREAD_STACK_MEM   (0)
#define CFG_CLI_THREAD_PRIORITY    osPriorityNormal
#define CFG_CLI_THREAD_STACK_SIZE  (configMINIMAL_STACK_SIZE * 12)	// 4 로 주면 CLI thread 가 죽어버리고, 8 로 주면 usStackHighWaterMark 가 0 가 되므로  최소한 12 이상을 주어라.

const osThreadAttr_t SCW_Cli_Thread_attr = {
		.name = 		CFG_CLI_THREAD_NAME,
		.attr_bits = 	CFG_CLI_THREAD_ATTR_BITS,
		.cb_mem = 		CFG_CLI_THREAD_CB_MEM,
		.cb_size = 		CFG_CLI_THREAD_CB_SIZE,
		.stack_mem = 	CFG_CLI_THREAD_STACK_MEM,
		.priority = 	CFG_CLI_THREAD_PRIORITY,
		.stack_size = 	CFG_CLI_THREAD_STACK_SIZE
};


/******************************************************************************
 * Thread Sensor attributes
 ******************************************************************************/
#define CFG_SENSOR_THREAD_NAME        "THREAD_SENSOR"
#define CFG_SENSOR_THREAD_ATTR_BITS   (0)
#define CFG_SENSOR_THREAD_CB_MEM      (0)
#define CFG_SENSOR_THREAD_CB_SIZE     (0)
#define CFG_SENSOR_THREAD_STACK_MEM   (0)
#define CFG_SENSOR_THREAD_PRIORITY    osPriorityBelowNormal
#define CFG_SENSOR_THREAD_STACK_SIZE  (configMINIMAL_STACK_SIZE * 8)

const osThreadAttr_t SCW_SENSOR_Thread_Attr = {
		.name = 		CFG_SENSOR_THREAD_NAME,
		.attr_bits = 	CFG_SENSOR_THREAD_ATTR_BITS,
		.cb_mem = 		CFG_SENSOR_THREAD_CB_MEM,
		.cb_size = 		CFG_SENSOR_THREAD_CB_SIZE,
		.stack_mem = 	CFG_SENSOR_THREAD_STACK_MEM,
		.stack_size = 	CFG_SENSOR_THREAD_STACK_SIZE,
		.priority = 	CFG_SENSOR_THREAD_PRIORITY
};


/******************************************************************************
 * Thread Annex attributes
 ******************************************************************************/
#define CFG_ANNEXE_THREAD_NAME        "THREAD_ANNEX"
#define CFG_ANNEXE_THREAD_ATTR_BITS   (0)
#define CFG_ANNEXE_THREAD_CB_MEM      (0)
#define CFG_ANNEXE_THREAD_CB_SIZE     (0)
#define CFG_ANNEXE_THREAD_STACK_MEM   (0)
#define CFG_ANNEXE_THREAD_PRIORITY    osPriorityNormal
#define CFG_ANNEXE_THREAD_STACK_SIZE  (configMINIMAL_STACK_SIZE * 8)

const osThreadAttr_t SCW_ANNEXE_Thread_Attr = {
		.name = 		CFG_ANNEXE_THREAD_NAME,
		.attr_bits = 	CFG_ANNEXE_THREAD_ATTR_BITS,
		.cb_mem = 		CFG_ANNEXE_THREAD_CB_MEM,
		.cb_size = 		CFG_ANNEXE_THREAD_CB_SIZE,
		.stack_mem = 	CFG_ANNEXE_THREAD_STACK_MEM,
		.stack_size = 	CFG_ANNEXE_THREAD_STACK_SIZE,
		.priority = 	CFG_ANNEXE_THREAD_PRIORITY
};


void sc_thread_cli (void *arg);

bool app_entry ()
{
	Thread_INIT_Handler = osThreadNew(scw_thread_init, NULL, &SCW_INIT_Thread_attr);
	assert (Thread_INIT_Handler != NULL);

	Thread_CLI_Handler = osThreadNew(scw_thread_cli, NULL, &SCW_Cli_Thread_attr);
	assert (Thread_CLI_Handler != NULL);

	Thread_SENSOR_Handler = osThreadNew(scw_thread_sensor, NULL, &SCW_SENSOR_Thread_Attr);
	assert (Thread_SENSOR_Handler != NULL);

//	Thread_ANNEX_Handler = osThreadNew(scw_thread_annex, NULL, &SC_ANNEXE_Thread_Attr);
//	assert (Thread_ANNEX_Handler != NULL);

	return true;
}
