/**
 ******************************************************************************
  * File Name          : cmds_board.c
  * Description        : This file is generated by 위대한 송 인재 on Aug 12, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

static void scw_cmd_pcreset (SYS_CMD_DEVICE_NODE* pCmdIO, int argc, char **argv)
{
	const void* cmdIoParam = pCmdIO->cmdIoParam;

	if (argc != 2) goto USAGE;

	if (!strcmp(argv[1], "on")) {
		HAL_GPIO_WritePin(PC_RESET_GPIO_Port, PC_RESET_Pin, GPIO_PIN_SET);
	}
	else if (!strcmp(argv[1], "off")) {
		HAL_GPIO_WritePin(PC_RESET_GPIO_Port, PC_RESET_Pin, GPIO_PIN_RESET);
	}
	else {
		goto USAGE;
	}
	return;

	USAGE :
	(*pCmdIO->pCmdApi->msg)(cmdIoParam, "USAGE : pcreset on/off"LINE_TERM);
	return;
}

static void scw_cmd_ssr1 (SYS_CMD_DEVICE_NODE* pCmdIO, int argc, char **argv)
{
	const void* cmdIoParam = pCmdIO->cmdIoParam;

	if (argc != 2) goto USAGE;

	if (!strcmp(argv[1], "on")) 	ssr1_on;
	else if (!strcmp(argv[1], "off")) ssr1_off;
	else 	goto USAGE;
	return;

	USAGE :
	(*pCmdIO->pCmdApi->msg)(cmdIoParam, "USAGE : ssr1 on/off"LINE_TERM);
	return;
}

static void scw_cmd_ssr2 (SYS_CMD_DEVICE_NODE* pCmdIO, int argc, char **argv)
{
	const void* cmdIoParam = pCmdIO->cmdIoParam;

	if (argc != 2) goto USAGE;

	if (!strcmp(argv[1], "on")) 	ssr2_on;
	else if (!strcmp(argv[1], "off")) ssr2_off;
	else 	goto USAGE;
	return;

	USAGE :
	(*pCmdIO->pCmdApi->msg)(cmdIoParam, "USAGE : ssr2 on/off"LINE_TERM);
	return;
}

static void scw_cmd_ssr3 (SYS_CMD_DEVICE_NODE* pCmdIO, int argc, char **argv)
{
	const void* cmdIoParam = pCmdIO->cmdIoParam;

	if (argc != 2) goto USAGE;

	if (!strcmp(argv[1], "on")) 	ssr3_on;
	else if (!strcmp(argv[1], "off")) ssr3_off;
	else 	goto USAGE;
	return;

	USAGE :
	(*pCmdIO->pCmdApi->msg)(cmdIoParam, "USAGE : ssr3 on/off"LINE_TERM);
	return;
}

static void scw_cmd_ssr4 (SYS_CMD_DEVICE_NODE* pCmdIO, int argc, char **argv)
{
	const void* cmdIoParam = pCmdIO->cmdIoParam;

	if (argc != 2) goto USAGE;

	if (!strcmp(argv[1], "on")) 	ssr4_on;
	else if (!strcmp(argv[1], "off")) ssr4_off;
	else 	goto USAGE;
	return;

	USAGE :
	(*pCmdIO->pCmdApi->msg)(cmdIoParam, "USAGE : ssr4 on/off"LINE_TERM);
	return;
}

static void scw_cmd_5v_sw1 (SYS_CMD_DEVICE_NODE* pCmdIO, int argc, char **argv)
{
	const void* cmdIoParam = pCmdIO->cmdIoParam;

	if (argc != 2) goto USAGE;

	if (!strcmp(argv[1], "on")) _5v_sw1_on;
	else if (!strcmp(argv[1], "off")) _5v_sw1_off;
	else goto USAGE;

	return;

	USAGE :
	(*pCmdIO->pCmdApi->msg)(cmdIoParam, "USAGE : _5v_sw1 on/off"LINE_TERM);
	return;
}

static void scw_cmd_5v_sw2 (SYS_CMD_DEVICE_NODE* pCmdIO, int argc, char **argv)
{
	const void* cmdIoParam = pCmdIO->cmdIoParam;

	if (argc != 2) goto USAGE;

	if (!strcmp(argv[1], "on")) _5v_sw2_on;
	else if (!strcmp(argv[1], "off")) _5v_sw2_off;
	else goto USAGE;

	return;

	USAGE :
	(*pCmdIO->pCmdApi->msg)(cmdIoParam, "USAGE : _5v_sw2 on/off"LINE_TERM);
	return;
}

static void scw_cmd_12v_sw1 (SYS_CMD_DEVICE_NODE* pCmdIO, int argc, char **argv)
{
	const void* cmdIoParam = pCmdIO->cmdIoParam;

	if (argc != 2) goto USAGE;

	if (!strcmp(argv[1], "on")) _12v_sw1_on;
	else if (!strcmp(argv[1], "off")) _12v_sw1_off;
	else goto USAGE;

	return;

	USAGE :
	(*pCmdIO->pCmdApi->msg)(cmdIoParam, "USAGE : _12v_sw1 on/off"LINE_TERM);
	return;
}

static void scw_cmd_12v_sw2 (SYS_CMD_DEVICE_NODE* pCmdIO, int argc, char **argv)
{
	const void* cmdIoParam = pCmdIO->cmdIoParam;

	if (argc != 2) goto USAGE;

	if (!strcmp(argv[1], "on")) _12v_sw2_on;
	else if (!strcmp(argv[1], "off")) _12v_sw2_off;
	else goto USAGE;

	return;

	USAGE :
	(*pCmdIO->pCmdApi->msg)(cmdIoParam, "USAGE : _12v_sw2 on/off"LINE_TERM);
	return;
}

static void scw_cmd_sht2x (SYS_CMD_DEVICE_NODE* pCmdIO, int argc, char **argv)
{
	const void* cmdIoParam = pCmdIO->cmdIoParam;

	if (argc != 1) goto USAGE;

	/* Gets current temperature & relative humidity. */
	float cel = SHT2x_GetTemperature(1);
	/* Converts temperature to degrees Fahrenheit and Kelvin */
	float fah = SHT2x_CelsiusToFahrenheit(cel);
	float kel = SHT2x_CelsiusToKelvin(cel);
	float rh = SHT2x_GetRelativeHumidity(1);
	/* May show warning below. Ignore and proceed. */
	(*pCmdIO->pCmdApi->print)(cmdIoParam, "%d.%dºC, %d.%dºF, %d.%d K, %d.%d%% RH\n"LINE_TERM,
			SHT2x_GetInteger(cel), SHT2x_GetDecimal(cel, 1),
			SHT2x_GetInteger(fah), SHT2x_GetDecimal(fah, 1),
			SHT2x_GetInteger(kel), SHT2x_GetDecimal(kel, 1),
			SHT2x_GetInteger(rh), SHT2x_GetDecimal(rh, 1));
	return;

	USAGE :
	(*pCmdIO->pCmdApi->msg)(cmdIoParam, "USAGE : sht2x"LINE_TERM);
	return;
}

static void scw_cmd_mute (SYS_CMD_DEVICE_NODE* pCmdIO, int argc, char **argv)
{
	const void* cmdIoParam = pCmdIO->cmdIoParam;

	if (argc != 2) goto USAGE;

	if (!strcmp(argv[1], "on")) mute_on;
	else if (!strcmp(argv[1], "off")) mute_off;
	else goto USAGE;
	return;

	USAGE :
	(*pCmdIO->pCmdApi->msg)(cmdIoParam, "USAGE : mute on/off"LINE_TERM);
	return;
}

static const SYS_CMD_DESCRIPTOR    Board_CommandTbl []=
{
		// Relay command..
		{"pcreset",       	scw_cmd_pcreset,		"\t\t- pcreset on/off"},
		{"ssr1",       		scw_cmd_ssr1,			"\t\t- ssr1 on/off"},	// Modem. 회로도는 Modem, board 의 실크는 Light 로 되어 있음. 나는 board 의 실크를 따른다.
		{"light",       	scw_cmd_ssr1,			"\t\t- light on/off"},	// Modem. 회로도는 Modem, board 의 실크는 Light 로 되어 있음. 나는 board 의 실크를 따른다.
		{"ssr2",       		scw_cmd_ssr2,			"\t\t- ssr2 on/off"},	// Lighting. 회로도는 Modem, board 의 실크는 Light 로 되어 있음. 나는 board 의 실크를 따른다.
		{"modem",       	scw_cmd_ssr2,			"\t\t- modem on/off"},	// Lighting. 회로도는 Modem, board 의 실크는 Light 로 되어 있음. 나는 board 의 실크를 따른다.
		{"ssr3",       		scw_cmd_ssr3,			"\t\t- ssr3 on/off"},	// Heater
		{"heater",    		scw_cmd_ssr3,			"\t\t- heater on/off"},	// Heater
		{"ssr4",       		scw_cmd_ssr4,			"\t\t- ssr4 on/off"},	// FAN1 & FAN2
		{"fan",       		scw_cmd_ssr4,			"\t\t- fan on/off"},	// FAN1 & FAN2

		// Switch command..
		{"_5v_sw1",     	scw_cmd_5v_sw1,			"\t\t- _5v_sw1 on/off"},
		{"_5v_sw2",     	scw_cmd_5v_sw2,			"\t\t- _5v_sw2 on/off"},
		{"_12v_sw1",     	scw_cmd_12v_sw1,		"\t\t- _12v_sw1 on/off"},
		{"_12v_sw2",     	scw_cmd_12v_sw2,		"\t\t- _12v_sw2 on/off"},

		// SHT2x command..
		{"sht2x",     		scw_cmd_sht2x,				"\t\t- sht2x"},

		// Audio command..
		{"mute",     		scw_cmd_mute,				"\t\t- mute on/off"},

};

bool cmd_board_add ()
{
	assert (SYS_CMD_ADDGRP(Board_CommandTbl, sizeof(Board_CommandTbl)/sizeof(*Board_CommandTbl), "board", ": board command group") == true);
	return true;
}


