/**
 ******************************************************************************
 * File Name          : cmds_system.c
 * Description        : This file is generated by 위대한 송 인재 on Aug 8, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

static void smb_cmd_scw (SYS_CMD_DEVICE_NODE* pCmdIO, int argc, char **argv)
{
	const void* cmdIoParam = pCmdIO->cmdIoParam;

	if (argc != 1) {
		goto USAGE;
	}

	do_scw_info_display = !do_scw_info_display;

	if (do_scw_info_display == true) {
		(*pCmdIO->pCmdApi->msg)(pCmdIO->cmdIoParam, CUI_ESC_CLR);
		(*pCmdIO->pCmdApi->msg)(pCmdIO->cmdIoParam, CUI_ESC_CUR_HOME); osDelay(1);
		(*pCmdIO->pCmdApi->msg)(pCmdIO->cmdIoParam, CUI_ESC_CUR_HIDE); osDelay(1);
	}
	else {
		(*pCmdIO->pCmdApi->msg)(pCmdIO->cmdIoParam, CUI_ESC_CUR_SHOW);
	}
	return;

	USAGE:
	(*pCmdIO->pCmdApi->msg)(cmdIoParam, "scw"LINE_TERM);
	return;

	return;
}

static void smb_cmd_show (SYS_CMD_DEVICE_NODE* pCmdIO, int argc, char **argv)
{
	const void* cmdIoParam = pCmdIO->cmdIoParam;

	if (argc != 2) goto USAGE;

	if (!strcmp(argv[1], "timer")) {
		(*pCmdIO->pCmdApi->msg)(cmdIoParam, " osTimerList"LINE_TERM);
		for (uint32_t i = 0 ; i < OS_TIMER_INDEX_END ; i++) {
			if (osTimerList[i].osTimerId == NULL) continue;
			(*pCmdIO->pCmdApi->print)(cmdIoParam, " %2d : %s \t%4d ms \t%s"LINE_TERM,			\
					i, (osTimerList[i].osTimerType == osTimerOnce)?"osTimerOnce":"osTimerPeriodic", osTimerList[i].timeout_tick, osTimerList[i].timer_description);
		}
	}

	if (!strcmp(argv[1], "intr")) {
		(*pCmdIO->pCmdApi->msg)(cmdIoParam, " IntrObjList"LINE_TERM);
		for (uint32_t i = 0 ; i < SCW_RTU_INTR_INDEX_END ; i++) {
			if (strlen(IntrObjEntryList[i].IntrName) < 15) {
			(*pCmdIO->pCmdApi->print)(cmdIoParam, " %2d : %10d \t%s \t\t%s"LINE_TERM,			\
					IntrObjEntryList[i].IntrNo, IntrObjEntryList[i].IntrCount, IntrObjEntryList[i].IntrName, IntrObjEntryList[i].IntrDesc);
			}
			else {
				(*pCmdIO->pCmdApi->print)(cmdIoParam, " %2d : %10d \t%s \t%s"LINE_TERM,			\
						IntrObjEntryList[i].IntrNo, IntrObjEntryList[i].IntrCount, IntrObjEntryList[i].IntrName, IntrObjEntryList[i].IntrDesc);
			}
		}
	}
	return;

	USAGE:
	(*pCmdIO->pCmdApi->msg)(cmdIoParam, " show timer/intr/");
	return;
}


static void smb_cmd_showuptime (SYS_CMD_DEVICE_NODE* pCmdIO, int argc, char **argv)
{
	const void* cmdIoParam = pCmdIO->cmdIoParam;
	uint8_t day, hour, min, sec;
	uint64_t tmp;

	tmp = uptime_counter;

	day = tmp /DAY_TO_SEC;
	tmp = tmp - (day*DAY_TO_SEC);

	hour = tmp/HOUR_TO_SEC;
	tmp = tmp - (hour*HOUR_TO_SEC);

	min = tmp/MIN_TO_SEC;
	tmp = tmp - (min*MIN_TO_SEC);

	sec = tmp;

	(*pCmdIO->pCmdApi->print)(cmdIoParam, " Uptime = %d days, %d hours, %d mins, %d sec"LINE_TERM, day, hour, min, sec);

	return;
}

static const SYS_CMD_DESCRIPTOR    System_CommandTbl []=
{
		{"scw",     		smb_cmd_scw,				"\t\t- scw"},
		{"show",     		smb_cmd_show,      			"\t\t- show timer"},
		{"uptime",     		smb_cmd_showuptime,      	"\t\t- uptime"},
		{"runtime",     	smb_cmd_showuptime,      	"\t\t- runtime"},
};

bool scw_cmd_system_add ()
{
	assert (SYS_CMD_ADDGRP(System_CommandTbl, sizeof(System_CommandTbl)/sizeof(*System_CommandTbl), "system", ": system command group") == true);
	return true;
}

