/**
 ******************************************************************************
  * File Name          : head_type.h
  * Description        : This file is generated by 위대한 송 인재 on Aug 8, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */


#ifndef INC_HEAD_TYPE_H_
#define INC_HEAD_TYPE_H_


typedef struct {
	uint32_t 		RCC_Intr_count;
	uint32_t 		DMA1_Chan_1_count;
	uint32_t 		DMA1_Chan_3_count;
	uint32_t 		DMA1_Chan_4_count;
	uint32_t 		DMA1_Chan_6_count;
	uint32_t 		DMA1_Chan_7_count;
	uint32_t 		DMA2_Chan_3_count;		// IAP Tx
	uint32_t 		DMA2_Chan_5_count;		// IAP Rx
	uint32_t 		ADC_Cplt_count;
	uint32_t 		PWM_PulseFinishedCallback;
	uint32_t 		EXTI9_5_count;
	uint32_t 		TIM4_count;
	uint32_t 		SPI1_count;
	uint32_t 		USART1_count;
	uint32_t 		USART2_count;
	uint32_t 		USART3_count;
	uint32_t 		UART4_count;
	uint32_t 		EXTI15_10_count;
	uint32_t 		TIM7_count;
	uint32_t 		TIM16_count;
	uint32_t 		TIM17_count;
	uint32_t 		RTC_Alarm_count;
} IntrObj_t;


typedef enum {
	BANNER_DSN = 0,
	BANNER_ECELL,
	BANNER_SMART,
	BANNER_PEE,
	BANNER_SHIT,
	BANNER_BALLET,
	BANNER_END,
} scw_banner_t;









#endif /* INC_HEAD_TYPE_H_ */
